### PR TITLE
fix: correct constructor tooltip and revise translation keys

### LINKED ISSUE #20: The tooltip for constructor is wrong
As shown below, the tooltip for constructor is for parameters.

https://github.com/typst-community/typst-docs-web/blob/a4c5ed871b8ffb1ac6ef00f07e98b42fa7165501/src/components/templates/TypeTemplate.tsx#L40-L43

Example: [official](https://typst.app/docs/reference/foundations/array/#constructor) / [jp](https://typst-jp.github.io/docs/reference/foundations/array/#constructor).

Besides, it's confusing that some translation keys use _parameter_ while others use _argument_.

https://github.com/typst-community/typst-docs-web/blob/a4c5ed871b8ffb1ac6ef00f07e98b42fa7165501/src/components/templates/FuncTemplate.tsx#L55-L58

### PR DESCRIPTION
**Pull request by YDX-2147483647**
This PR corrects the tooltip for constructors in the TypeTemplate.
Resolves #20

This PR also adds a new translation key `constructorDescription`.
I copy the en-US description from [the official docs](https://typst.app/docs/reference/foundations/array/#constructor) (this is just a plain sentence and I don't think it's even copyrightable), and use a machine translator to generate its ja-JP version. Please review it!

> **en-US:** If a type has a constructor, you can call it like a function to create a new value of the type.
> **ja-JP:** ~~型がコンストラクタを持っていれば、その型の新しい値を生成する関数のように呼び出すことができます。~~ (See comments below)

When I was adding that key, I found that the existing keys were chaotic and contained some minor errors. Therefore, I reorganized them. Specifically:

- Classify translation keys into categories
- Correct a few errors on singular/plural forms in `en-US.tsx`
- Merge the duplicate keys `definition` and `definitionTooltip` into `definitions`
- Refactor a switch-key-case-return into a `Record<Key, string>`, making it sensitive to missing keys

### CODE REVIEW

File: src/translation/ja-JP.tsx [hunk 1]
```diff
@@ -131,17 +113,32 @@ export const Translation: TranslationComponent = (props) => {
...
 				</Fragment>
 			);
-		case "definitionTooltip":
+
+		case "constructor":
+			return <Fragment>コンストラクタ</Fragment>;
+		case "constructorDescription":
+			return (
+				<Fragment>
+					型がコンストラクタを持っていれば、その型の新しい値を生成する関数のように呼び出すことができます。
```
Comment (3w36zj6) [inline src/translation/ja-JP.tsx]:
```suggestion
					コンストラクタを持つ型の場合、関数のように呼び出すことで、その型の新しい値を作成できます。
```

@typst-community/jp
Do you have any suggestions for a more natural translation?

Comment (YDX-2147483647) [reply src/translation/ja-JP.tsx]: I've committed this version because it has been three days.
If you or anyone has a better idea, we can re-update it.
